/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String helloFromGradle() {
        return "Hello from Gradle.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().helloFromGradle());
    }
}
